### PR TITLE
Improved legibility of the "Get Code" output.

### PR DESCRIPTION
**Pull request by Brugman**
Refactoring of #582.

Added 2 PHP indentation fixes.

### CODE REVIEW

**Comment by tw2113** [comment]
Any chances you can provide before/after screenshots? I am a bit wondering about the removal of some \n characters and such. With this area, where we're outputting into a textarea, all whitespace makes a difference in what gets rendered.

**Comment by Brugman** [comment]
Before
before
https://gist.github.com/Brugman/69d0f756da5b24ae1edfcf21ae4535f5

After
after
https://gist.github.com/Brugman/24af08fbd1775a1c26c428801bcd306f

Screenshots taken on Win 7, Firefox 50.1.0.

I've tested a few different configurations (default, anti-default and a mixture) but not every single possible config. I'm confident the code won't break, but there might be a combination in which it isn't perfectly tabbed.

The (alpha) line 190 and 312 \n got replaced by an HTML line break on (feature) line 259 and 428. This way each cpt starts with a blank line instead of forcing one after itself, that makes it look cleaner if there's only 1 cpt/tax in the list. It also clears the HTML from the 2 foreaches, separating PHP and HTML a bit more.

I wanted to change this because the current snippets are imo too messy to paste straight into my themes/plugins.

**Comment by Brugman** [comment]
A next step I'd like to take is [align the variables](https://gist.github.com/1d176161cdbf37f835260805dfcc3183). It would probably require 1 or 2 helper functions, make it a little heavier and add a little complexity to the source, but it's for a good cause and its a single page, not a hook on init.

**Comment by tw2113** [comment]
Mostly just worried that things may or may not output enough to prevent a PHP fatal error if copy/pasted/saved and not reviewed first, but at the same time, hopefully people aren't doing that on prod. Also, most of our users utilize the plugin as is, instead of as a generator for code, so it's not a frequent problem and can be addressed at that time.

**Pull request merged**
