### PR TITLE
first pass at performance tweaks for preserved labels

### PR DESCRIPTION
**Pull request by tw2113**
first pass to address concerns in #650

### CODE REVIEW

**Comment by alex-solovyev** [comment]
Hi @tw2113,

I've replicated the code for taxonomies as well and it's much better now
screen shot 2017-10-06 at 12 01 19

That could be even better if there would be two separate functions for type_posts & taxonomies instead of one cptui_get_preserved_label_second.

Regards,
Alex

**Comment by tw2113** [comment]
Good to know that this looks like its effects are as intended. I'll need to clean up some details and will consider the split between types and taxonomies instead of one function.

Thanks for working with me through the topic and providing feedback. As mentioned yesterday, I still intend to give you credit with the change :D

**Comment by alex-solovyev** [comment]
The only downside I can see with this approach is that the function cptui_get_preserved_label_second will be called even for users who populated all additional labels. FYI I've also updated my PR.

**Comment by tw2113** [comment]
Definitely true, but it's going to be just however many post types/taxonomies they have registered instead of for each label, which is still better than it was.

**Comment by tw2113** [comment]
See a54ea8700d156a77fbf0f1e056c72b22b48d9cd7

**Pull request closed without merging**
