### PR TITLE
Update custom-post-type-ui.php

### PR DESCRIPTION
**Pull request by arshidkv12**
$post_type is null.

### CODE REVIEW

**Comment by tw2113** [comment]
Is this solving potential PHP notices coming in or something similar? Just trying to make sure I understand the need for this change.

**Comment by arshidkv12** [comment]
I think, it is unused code.

**Comment by tw2113** [comment]
Actually, looking closer, it's supposed to be there, but I have the wrong variable referenced, so I'm accidentally not allowing for custom taxonomy rest controller classes.

Willing to give you some change props if you want to instead change the `$post_type` variable to be `$taxonomy`. Chances are I copy/pasted at the time and it's just now getting noticed.

I'm also going to change the branch this PR is against to the newly created release193 branch

**Comment by tw2113** [comment]
Opened issue to track this one https://github.com/WebDevStudios/custom-post-type-ui/issues/820

**Comment by tw2113** [comment]
While I see you're around a bit yet today, would love to see this amended. It'd make for a great 1.9.3 release which would be as early as next week.

**Comment by tw2113** [comment]
Pushed up the changes myself, but giving you props for helping notice it. I appreciate that.

**Pull request closed without merging**
