### PR TITLE
Introduce static analysis

### PR DESCRIPTION
**Pull request by szepeviktor**
@tw2113 Here is the new test.

### CODE REVIEW

**Comment by szepeviktor** [comment]
@tw2113 Could you help in this mistery?

```
 ------ ------------------------------------------------------------------------ 
  Line   inc/utility.php                                                         
 ------ ------------------------------------------------------------------------ 
  879    Call to function array_key_exists() with string and string will always  
         evaluate to false.                                                      
  879    Result of && is always false.                                           
 ------ ------------------------------------------------------------------------ 
```

**Comment by szepeviktor** [comment]
Resolved! See the last commit.

**Comment by tw2113** [comment]
Given that this would be getting run at the travisci level, is it meant to reject if not all cases are being met? or just report for information sake?

In terms of general development, I've traditionally been relying on PHPStorm's code inspections to address overall issues of this style.

We DO have tests, they're just not extensive or cover majority of the plugin.

I think I'd prefer that this PR simply pull in the necessary changes for phpstan to get run, but not include fixes that were already identified by it. It would remove a good amount of 27a81780f33673f2430072ba8f65e51c7cb9a741 but I think that's the only commit that touches files outside the test suite and the travis config.

**Comment by szepeviktor** [comment]
> is it meant to reject if not all cases are being met? or just report for information sake?

If you enable TravisCI for PR-s of course it would reject any PR having phpstan Level 4 errors.

Please `git cherrypick` any commits from this PR. I leave it to You!

**Comment by szepeviktor** [comment]
I am campaigning with phpstan lately: frameworks, WordPress plugins, composer packages. See my profile where I've opened issues/PRs.

Having phpstan in your CI has a huge benefit but it needs some work. No one looks and the CI output so informational tests are useless.

Static analysis is like have additional 100 pair of eyes.

**Comment by szepeviktor** [comment]
One more thing, I work for developer team as an _error prevention officer_

I talk them into these 3 zero-coverage CI tests:

1. syntax check
1. coding standards
1. static analysis

They don't have to do anything but seeing the results.

**Pull request closed without merging**
