### PR TITLE
Typo in support question string.

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by tw2113** [comment]
Thanks for noticing that and doing a PR against the 1.2 branch Pedro :)

**Comment by pedro-mendonca** [comment]
You're welcome.
I'm finnishing translating the latest added strings and pulling in a minute.
I've read in the code that you are moving to WordPress.org translation platform. For now I'll keep contributing here as you maintain the .po/.mo files. If you wish the translations to be sent just in WordPress site, please let me know.

**Comment by tw2113** [comment]
I'm still accepting and distributing from the repo manually until I know how that whole setup works.

**Comment by pedro-mendonca** [comment]
Ok than, I'll keep doing it here as usual.
:+1:

**Pull request merged**
