### PR TITLE
Added .cptui-taxonomy-submit class to all cpt_submit inputs

### LINKED ISSUE #711: The no_associated_type alert should be latched to both Tax Submits
Hello,

The jQuery alert to block submit when there's no Post Type is only attached to .cptui-taxonomy-submit and should also be attached to the .cpt_submit one as well. Currently the first 'Save Taxonomy' won't trigger the alert.

Submitted a quick PR.

Cheers

### PR DESCRIPTION
**Pull request by garrett-eclipse**
Fixes #711
Added .cptui-taxonomy-submit class to all add/save primary buttons.

### CODE REVIEW

**Comment by tw2113** [comment]
Forgot to mention/request that the PR be against the release160 branch. Sorry about that Garrett

**Comment by garrett-eclipse** [comment]
No worries, I think that should do it just switched the merge branch there. Let me know if there's any issue with that.
*Note: As admin on the project if others PR to the wrong branch you have the ability to fix it on the PR.

**Comment by tw2113** [comment]
Learned something new, you can change PR destinations without having to close/re-open new.

**Comment by garrett-eclipse** [comment]
I only learned about it a month ago and has saved me from redoing sooo many PRs ;)

**Pull request merged**
