### PR TITLE
Added missing help text and `<label>` html tags

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by pedro-mendonca** [comment]
@tw2113 would you prefer I'll do this on 1.1 branch?

**Comment by pedro-mendonca** [comment]
I made this PR https://github.com/WebDevStudios/custom-post-type-ui/pull/268 also on branch 1.1.0 as you can see here, you can now test it in both branches. Probably this one will not be necessary and shall be closed now.

**Comment by tw2113** [comment]
Closing as it got merged in a different way with some testing I was doing.

**Comment by tw2113** [comment]
Pedro, if you could test master once more quick to help confirm it's working as expected, I'd appreciate it.

**Comment by pedro-mendonca** [comment]
Hi,
I think everything is as expected now.
The .pot in master branch have some strings from /inc/listings.php that isn't in the folder. In 1.1 branch I had the same problem as the files is *included* and returns an error.

**Comment by tw2113** [comment]
Yeah, the listings.php is something coming in 1.1, and it snuck into 1.0.6 because the file was still in the folder. Those ones you can ignore if you want, you can translate if you want, but they won't be applied to anything yet.

**Comment by pedro-mendonca** [comment]
I've been translating for pt_PT in 1.1 branch and that file ain't there either.

**Comment by tw2113** [comment]
I must have forgot to add the file to the repo, it should be in there now

**Comment by pedro-mendonca** [comment]
:+1:

**Pull request closed without merging**
