### PR TITLE
de_DE_formal added alongside a few typo fixes for the colloquial de_DE version

### PR DESCRIPTION
**Pull request by rpkoller**
a first draft for the formal de_DE language version. alongside a few typo fixes were discovered and fixed in the de_DE version

### CODE REVIEW

**Comment by rpkoller** [comment]
@tw2113 anything wrong with that pull request? ;) it is idling for a few weeks now and meanwhile also a merge conflict slipped in after you've updated the german po and mo file in the 1.2 branch.

**Comment by tw2113** [comment]
No. It just slipped my attention. Sorry about that.

On that note, I did change the textdomain last night to better help with future localization through what WordPress.org is doing. The domain now matches the slug from our repo on .org. May not be a bad idea to refresh the PR as necessary and I can get it pulled in afterwards.

**Comment by rpkoller** [comment]
yep the textdomain i've noticed. ok i think i figured the merge conflict out. but please dont commit yet. i have to do a few checks first. guess it will change a little more.

**Comment by rpkoller** [comment]
@tw2113 ok pushed the latest changes up to my cptui copy on github. no merge conflicts anymore and i've update from source and added the new strings. could be commited now.

**Comment by tw2113** [comment]
Thanks.

**Pull request merged**
