### PR TITLE
add WPGraphQL support if available

### PR DESCRIPTION
**Pull request by tw2113**

### CODE REVIEW

**Comment by jasonbahl** [comment]
@tw2113 I just recently released an update to WPGraphQL for Custom Post Type UI that fixed some issues with the fields being required/not-required. 

See the example GIF of this new behavior:

show-in-graphql-cptui

Now the `graphql_single_name` and `graphql_plural_name` are only shown and required if `show_in_graphql` is set to true. If you want a Post Type or Taxonomy to be hidden from GraphQL, the `graphql_single_name` and `graphql_plural_name` are not required. 

The JavaScript I used to handle this: https://github.com/wp-graphql/wp-graphql-custom-post-type-ui/pull/16/files#diff-5cf0f43eb7881516f027acf7b1784defe9675b3fbf483c15a562859aa0597ca6R274-R326

I think it would be good to include something similar to make sure things work correctly.

**Comment by tw2113** [comment]
Saw that, as the version I ultimately merged in to what will be the final release had that javascript in place. However, at the moment I have removed it.

That said, you chiming in has me thinking that we should actually make sure to have users fill those in, if Show In is true. Can't have a case of Show in is true, and the rest are empty. Otherwise, undue support requests for why things aren't working.

Sounding right?

**Comment by jasonbahl** [comment]
Exactly. Issues will be reported if users can set the Post Type or Taxonomy to `show_in_graphql` but leave those blank. 

The v1.2.0 release of the WPGraphQL for CPT UI plugin solved the following issues: 

- https://github.com/wp-graphql/wp-graphql-custom-post-type-ui/issues/14
- https://github.com/wp-graphql/wp-graphql-custom-post-type-ui/issues/12
- https://github.com/wp-graphql/wp-graphql-custom-post-type-ui/issues/11
- https://github.com/wp-graphql/wp-graphql-custom-post-type-ui/issues/10
- https://github.com/wp-graphql/wp-graphql-custom-post-type-ui/issues/9
- https://github.com/wp-graphql/wp-graphql-custom-post-type-ui/issues/8

**Comment by tw2113** [comment]
I will spare both of us headache then and get that back in place. Thanks for the feedback Jason.

**Comment by jasonbahl** [comment]
We should also rename the class. 

Using the same `WPGraphQL_CPT_UI` class creates fatal errors for users that already have `WPGraphQL for Custom Post Type UI` active. 

```
PHP Fatal error:  Cannot declare class WPGraphQL_CPT_UI, because the name is already in use in /Users/jason.bahl/Local Sites/wpgraphql/app/public/wp-content/plugins/custom-post-type-ui/external/wpgraphql.php on line 10
```

Consider changing the class name to something like `CPTUI_WPGraphQL` instead?

Additionally, maybe in the `init` method, consider a check like so, preventing the new functionality if the old extension still exists: 

```php
if ( class_exists( 'WPGraphQL_CPT_UI' ) ) {

  add_action( 'admin_notices', function() {
    ?>
    <div class="notice notice-error">
        <p><?php _e( 'Custom Post Type UI has support for WPGraphQL. Please de-active the WPGraphQL for Custom Post Type UI extension to proceed.', 'custom-post-type-ui' ); ?></p>
    </div>
    <?php
  } );
  
  // Bail early before instantiating the other hooks. We don't want to instantiate this plugin while the extension is still active
  return;

}
```

**Comment by jasonbahl** [comment]
this code will also conflict: 

```php
add_action( 'plugins_loaded', 'init_wpgraphql_cptui' );

function init_wpgraphql_cptui() {
	$wpgraphql_cpt_ui = new WPGraphQL_CPT_UI();
	$wpgraphql_cpt_ui->init();
}
```

Should change the function name from `init_wpgraphql_cptui` to perhaps `init_cptui_wpgraphql` for the same reason as above

**Comment by tw2113** [comment]
Noted on all parts, and I'll get these implemented before release. Probably won't be pushed out officially till next week, with it being Friday and all. :D

**Comment by jasonbahl** [comment]
@tw2113 sounds good! 

I can submit these changes as a PR too. Whatever works.

**Comment by tw2113** [comment]
Since we're in a brand new file and in a sense a brand new area I'm calling "external" for lack of better naming, I took the opportunity to namespace the file. Even then though, I renamed the class as well.

Other notes: added the admin notice like suggested, just to help avoid too many fields, but it shouldn't fatal error regardless.

All changes can be seen in 17806b8 and I'm confident we're good to release soon :D

**Pull request merged**
