### PR TITLE
Add latest strings related to renaming/migrating/updating taxonomies

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by tw2113** [comment]
For what it's worth Pedro, it's not super important to keep these things PR'd and in sync very early on. The earlier in the release cycle, the more you'll have to update due to line changes etc, as we're still going to have a lot likely changing. If done towards the end of a cycle after most of the work is done, less times to have to update it all.

That said, you can keep your local branch in sync and the translations updated locally, then issue the one final PR once all is done.

**Comment by pedro-mendonca** [comment]
Yes, I did created this branch according to your lates guidelines, I've pulled this as I made a check on this today, but you're right of course, better make it all at once.

**Comment by tw2113** [comment]
I appreciate all the hard work to make sure the translations are uptodate, don't mistake me there. Just trying to save you from having to do too much repeated work :)

**Comment by pedro-mendonca** [comment]
Yep, I understood :+1:

**Pull request merged**
