### PR TITLE
Add generic GitHub headers

### PR DESCRIPTION
**Pull request by pedro-mendonca**
This will make the branch compatible with GitHub Updater (https://github.com/afragen/github-updater) to help branch switching and updating from github.

### CODE REVIEW

**Comment by tw2113** [comment]
While the developer in me likes this type of thing, majority of the CPTUI users aren't that much of coders. With the releases on wordpress.org, I actually remove things like the unit test stuff and composer.json. The nice thing with those is that they're all separate files that I can easily remove. With this type of thing, I'd need to manually update the file any time I want to push up an update for wordpress.org.

**Comment by pedro-mendonca** [comment]
Are you sure about the need to remove these headers to push it to Wordpress repo?

I'm actually using some plugins that have this, and I found it after install GHU, because it identifies with an icon which ones include this headers.

About the majority of users not using this header, it won't harm either, as it's just a generic info on it's github home.

You should try it, great to quickly switch between branches, specially good when there are a lot of branches and you need to test one.

**Comment by tw2113** [comment]
It doesn't need to not be there to be pushed up to wp.org, but it's also useless stuff for wp.org, which is the targeted audience for the plugin

**Comment by tw2113** [comment]
I'm willing to settle on this solution. Give this its own branch that I will do what I can to update each time there's a new version that gets released.

https://github.com/WebDevStudios/custom-post-type-ui/tree/master-github

It won't be the branch I take from for updating wordpress.org, so I won't need to worry about editing this spot each time :)

**Comment by pedro-mendonca** [comment]
It's a bit confusing and a more time consuming, but you should know that :)

**Comment by tw2113** [comment]
it'll take a few extra commands from the terminal from me to get updated, which is acceptable on my part. I still don't think most people installing from WP.org is going to even notice/care, and those who participate here are going to be fine.

**Pull request closed without merging**
