### PR TITLE
Proper TravisCI config

### PR DESCRIPTION
**Pull request by szepeviktor**
- allowed failures
- PHP 5.6

### CODE REVIEW

**Comment by szepeviktor** [comment]
@tw2113 Could you help in starting Travis in PR-s?

**Comment by tw2113** [comment]
For my clarity, and note i'm not against the changes, are these needed changes for the travisci configuration or are they just nice to haves?

Related to that, we'd want to have the changes PR'd against the release170 branch and not master.

**Comment by szepeviktor** [comment]
- allowed failures are not configured properly, thus the do not allow failures
- tests do not run on PHP 5.6
- travis config is really hard to read

**Comment by szepeviktor** [comment]
I've hacked till it started: https://travis-ci.org/szepeviktor/custom-post-type-ui/builds/565564869

**Comment by szepeviktor** [comment]
Could it be that unit tests are not ready?

**Comment by tw2113** [comment]
I'm willing to roll with whatever help you can provide, if you could issue a fresh PR on the `release170` branch. I have some time that I may spend with CPTUI in general on friday which would give me some ample time to try things out here.

Regarding unit tests, we don't have much for them, and most are for just https://github.com/WebDevStudios/custom-post-type-ui/blob/master/classes/class.cptui_admin_ui.php last I checked.

**Comment by szepeviktor** [comment]
Okay. I cook up some tests for you.

**Pull request closed without merging**
