### PR TITLE
Translate only neccessary label (performance issue)

### PR DESCRIPTION
**Pull request by alex-solovyev**

### CODE REVIEW

**Comment by tw2113** [comment]
Hi @alex-solovyev 
Definitely not against touching up on this function, especially if there's notable performance gains to be had, however I am not sure I agree with the proposed approach.

I know for sure I don't want the text domain passed through the translation functions as a variable. Every time I've checked, that's considered bad practice. On top of that, that's a constant value so it's fine to hard code.

Second, the strings to translate themselves should NOT be passed as a variable. The gettext functionality can't parse/interpret PHP.

Looking back at this function again, I could see potential improvements in performance by separating things out in this way. First, make a function that returns the array as a whole, and then a second one that grabs that array, and returns just the intended key. Alternatively, perhaps just return the whole array and store in a variable, and then simply refer to the index intended at the point of needing it. It'd save some function calls.

**Comment by alex-solovyev** [comment]
Hi @tw2113,

Thanks for your feedback. I've updated the pull request.

**Comment by tw2113** [comment]
Still going to have issue with passing the intended string for translation as a php variable.

https://github.com/WebDevStudios/custom-post-type-ui/pull/650/files#diff-bcebe73651fb15dba013e059aa8b6a7dR859

The more I have a chance to mull over this one, the more I'm seeing issue with trying to adjust this so that it still works, but doesn't do quite so much repetition.

Out of curiosity, do you have any sort of measure of how much performance gain was made from trying to optimize this area of the plugin? It looks like it's not even guaranteed to be used, and only will if no custom label is provided for the preserved items.

**Comment by alex-solovyev** [comment]
Here are screenshots from qcachegrind (relative measure).
Before:
screen shot 2017-10-05 at 15 59 40
screen shot 2017-10-05 at 15 59 55

After:
screen shot 2017-10-05 at 16 04 57

10% of page loading time before and less than 1% after the mod.

**Comment by alex-solovyev** [comment]
@tw2113 I see your point. I'll amend the PR shortly.

**Comment by tw2113** [comment]
Not denying the results shown, as that is hard evidence. I am wondering how many post types you presently have as well as if you have filled in all the labels.

I do see this is one that's run during the actual initialization/registration. For a moment I was wondering if I could move it to the settings save point, but that would end up filling in all the label fields, and cause potential panic. :D

**Comment by alex-solovyev** [comment]
3 custom post types, additional labels are not populated, only the plural & singular labels. 
What do you think about adding a "switch" statement for the labels, so that only one is translated each function call?

**Comment by tw2113** [comment]
I would need to see an example of what you're thinking there.

From my understanding, the biggest bottleneck here would be the fact that the translations are simply read from the associate `.mo` file. In terms of the implementation with CPTUI, the biggest bottleneck is that it's a dynamic spot and the same function is used many times for each post type and potentially many labels.

Technically, the best suggestion here would be to fill in the labels. However, I know not everyone wants to do that. I need to brain over it a bit more, but I believe it should be possible to reduce the translation part, while still keeping the dynamicness and placeholder values. Just a matter of changing when the sprintf parts occur.

Will see what I can come up with for how I'd ideally like to see it happen. Regardless of if it comes from a PR directly from you, or just a retooling, I'm planning to give you credit for the help. Just need to sit down and think it through a bit more.

**Comment by alex-solovyev** [comment]
I've amended the code.

screen shot 2017-10-06 at 00 52 38

**Comment by tw2113** [comment]
Hey @alex-solovyev can you pull a copy of https://github.com/WebDevStudios/custom-post-type-ui/tree/preserved-label-performance and run it through your performance tests with qcachegrind? I had some time this evening and wanted to give it a go with how I'd attempt to improve on the issue.

Regarding the last commit, until I know better and can assuredly bump minimum PHP version numbers, we have to keep the plugin at PHP 5.2. That provides conflict with your use of anonymous functions in the label providing function.

You can see what changes I tentatively made at https://github.com/WebDevStudios/custom-post-type-ui/pull/652/files

**Comment by alex-solovyev** [comment]
@tw2113 I've pushed a new version using the switch. the performance looks good and there is no anonymous functions.

screen shot 2017-10-06 at 13 09 43

**Comment by tw2113** [comment]
Went with the version I worked up, but I still gave you props for everything, as I do appreciate you bringing up the issue as well as the work above to attempt addressing it.

See a54ea8700d156a77fbf0f1e056c72b22b48d9cd7

**Comment by alex-solovyev** [comment]
OK, thanks

**Comment by alex-solovyev** [comment]
btw, do you have a release date for the new version?

**Comment by tw2113** [comment]
No release date target planned at the moment

**Pull request closed without merging**
