### PR TITLE
Allow labels to be translated in the theme

### PR DESCRIPTION
**Pull request by somewebmedia**

### CODE REVIEW

**Comment by somewebmedia** [comment]
@tw2113 Hey Michael, I just realised there is a branch `release160`, would you like me to make the PR to that branch instead?

**Comment by tw2113** [comment]
Good day @somewebmedia 

Thank you for your interest in contributing to CPTUI, and especially on a topic such as internationalization/localization. Below are my notes based on what I can see and identify as concerns.

Biggest thing is that we shouldn't be trying to translate variables. While PHP can parse the information/code/etc, the Gettext functionality in WordPress core does not. I did a quick test just to help confirm, using Poedit and some basic strings, and I was either not getting the text at all in the resulting .pot file or I was getting a literal "$test" as the string. What I stored in `$test` was "some string". This is a large part why we're sort of in a tough spot since we store all the CPT/Tax labels in the database.

Not sure why changing plurality labels to be based off of new variable and key. Located at https://github.com/WebDevStudios/custom-post-type-ui/pull/708/files#diff-bcebe73651fb15dba013e059aa8b6a7dR359 and https://github.com/WebDevStudios/custom-post-type-ui/pull/708/files#diff-bcebe73651fb15dba013e059aa8b6a7dR537 Is it because we wouldn't be able to rely on previous values somehow?

Unlike the text to be translated, I do believe the text domain can be dynamic/variable based so I'm not completely against the new constant. However I would probably personally lean more towards doing a filter for that instead of defining a new constant that we have to maintain. This would allow for individual site owners to take control of that spot a bit more, but also not suddenly remove all those labels for people who already use a translated copy with their own site. Much like with WordPress core, I do try to avoid breaking backwards compatibility whenever possible. Beyond that, the other issue would be having a given theme's po/mo files become aware of these new strings from within the plugin so that it can translate from their own location.

All in all, the biggest issue is the variables and how they're not going to translate, with a sub-issue of changed out text domains not being recognized like needed.

**Comment by somewebmedia** [comment]
Hey @tw2113, thanks for the quick reply.

I did not quite understand the first part, with the `$test`. Can you tell me how to re-create that test?

I changed the `$label_plurality` to use the labels from the new variable because that new variable is already translated above, and we want to use the translated one and combine it with the preserved labels that are also translated below.

I'm up for the use of filter, but it should by default be the theme's textdomain, so the CPTUI comes automatically ready for translation.

> Beyond that, the other issue would be having a given theme's po/mo files become aware of these new strings from within the plugin so that it can translate from their own location.

Because we use the theme textdomain, the theme's po/mo files are automatically aware of it. So if there is a translation in them, they will use it, if not, the untranslated label will be shown.

Let me make a change to use a filter instead of a constant.

**Comment by tw2113** [comment]
My "$test" bits above were just to illustrate passing any sort of variable to the `__()` functions. Just like in this spot: https://github.com/WebDevStudios/custom-post-type-ui/pull/708/files#diff-bcebe73651fb15dba013e059aa8b6a7dR377

As is that wouldn't work, the string value that shows up in the pot/po file would be literally "$label" and not it parsed out to the value stored in the original variable.

Noted on the plurality spot.

I must respectfully disagree that anything should default to something outside of our plugin's textdomain. The preserved labels are only used if no value is provided for a label that has the slug in it. For example "Edit Thing". However, as is in those situations, the site owner should be providing their own version. Do note that we realize this still falls short of any site that is more than English and 1 other language in the admin area. We haven't found a good solution for that still. That said, changing the text domain all of a sudden for those preserved label spots would undo all the work for them, that's been done over at https://translate.wordpress.org/projects/wp-plugins/custom-post-type-ui I would rather help someone use a filter to change the domain for that spot, rather than force it on everyone. This is the backwards compatibility I refer to.

What tools are you using for your translations? From my experiences, there's no guarantee that things will automatically be known. Something like Loco Translate potentially would pick things up, the next time it ran a scan of the files, but even then, things would need to be saved as well to have the binary .mo files regenerated. I can't say it's impossible and things wouldn't be noticed, but I can confidently say it's a case by case basis.

In the end, we still have the variables being passed to Gettext issue to deal with, and at least part of the time, depending on tools used, having the changed textdomain spots get recognized. One last bit, you don't need to worry about touching the spots found in `cptui_get_preserved_label()` as that function has been marked deprecated and we're not presently using it. The plural version of the function name, right below it, `cptui_get_preserved_labels()` is used.

**Aside**
For a little bit of insight to what's been going on in my head for awhile, I want to try my hand at a different translation approach. It is in no way set in stone or begun, but I feel we need to do something. :)

Yes we hardcode strings in the database, and will probably never get away from that either, without very purposely breaking things. However, my head is envisioning a separate addon that uses the filters already in place, and likely some different option pages that list out each available label, and provide a language selector based on the installed languages for the current site. Site owner could fill in the labels as appropriate to the chosen language, and hit save. When it comes time to register the given post type, we would fetch those saved values, extract out the language based on the current users' chosen language, and filter in those labels in to the arguments for the post type.

It would admittedly be something separate from other translation plugins and tools, but if my mental logic is correct, it would technically work.

**Pull request closed without merging**
