### PR TITLE
Tired of fixing this everytime I upgrade ... its just a warning that …

### PR DESCRIPTION
**Pull request by supercleanse**
…the indexes dont exist

I don't know if this is an appropriate fix or not but I keep getting notices on my development server whenever I update your plugin. It would be great to either get this merged in or otherwise fix this so I'm not wasting time editing code everytime I update it.

Thanks! Blair

### CODE REVIEW

**Comment by tw2113** [comment]
Hi Blair.

Original issue related regarding things: #275

Some quick notes.
1. We'll want to issue a PR against the Alpha branch, not Master.
2. We're planning to release version 1.4.0 this evening, so you have some good timing. However, it will definitely delay any sort of PR acceptance for a little while.

I am curious if re-saving and/or temporarily saving those two spots with a different value would fix the issue with the notices, to get them filled in with something for an index.

Note, that's not me disregarding the issue as a whole. I want to get them cleared more than anyone. The issue is that pre-1.0.0 settings used numeral string '0' for a value, and empty() evaluates to true with. Thanks PHP. It caused issues around the time of 1.0.x and thus I reverted and accepted some php notices.  That said, I'm at a point where I think we could give it a go again, as majority of people are at a version above where we altered the saved values and eliminated using '0' alltogether.

I'm going to run some tests on some things, and see about how effective it'd be to use empty() vs isset() like in your PR above. I want to try and make sure that I won't inadvertantly break as much as possible for anyone who may still upgrade from pre-1.0.0

**Comment by supercleanse** [comment]
That's fine ... this was just a quick and dirty fix that I was able to do on my end ... so do what you have to do. I'm just trying to bring this issue to light :) ... and point at where it is. As for re-saving, etc I'm not sure ... that may fix it? But either way it's always helpful to have some defensive code in place in case this condition can actually be triggered imho :) ... Anyway, good luck with the release!

**Comment by tw2113** [comment]
Can you try the alpha branch as of tonight? Not a direct merge, but I'd be willing to give some props in the changelog. It's going to be 1.4.0 release plus changes related to this, so you shouldn't experience much breakage at all.

Regarding the resaving, at least from what testing I've done over the year and a half, seemed to fill in and create the index, thus stopping the undefined index part.

**Comment by tw2113** [comment]
Should be getting fixed for good in 1.5.0, which we are aiming or at the very start of 2017.

If you want to try out the alpha branch, which is what has 1.5.0 in it at the moment, would love confirmation of fixing. No worries if you don't have a site that would suffer from it though.

**Pull request closed without merging**
