### PR TITLE
Add generic GitHub headers

### PR DESCRIPTION
**Pull request by pedro-mendonca**
This will make the branch compatible with GitHub Updater (https://github.com/afragen/github-updater) to help branch switching and updating from github.

### CODE REVIEW

**Comment by tw2113** [comment]
Closing as a duplicate of #269

**Comment by pedro-mendonca** [comment]
Just to clarify, this wasn't duplicate, if you did wanted this on your plugin, it was ment to be on both branches with different branch name to allow branch switch easily.

**Comment by tw2113** [comment]
Ah, good point with that. However, if I decide to go with it anyway, it'll get taken care of via merges between branches. So no worries there. I am leaving the other one open at the moment, for what it's worth :)

**Comment by pedro-mendonca** [comment]
Ok, thanks. :+1: 
I think I'll need to revert the commit to leave the path clear to pull further stuff. I'll do it later on.

**Pull request closed without merging**
